### ISSUE TITLE
docs: Update README.md

### ISSUE THREAD

**Issue by programmer290399** [programmer290399/pyqna#1]
## TODO:
- [ ] Add the following shields from [sheilds.io](https://shields.io/):
     - [ ] PyPi version 
         ![pypi](https://img.shields.io/pypi/v/pyqna?style=for-the-badge) 
     - [ ] CI Status 
          ![TESTS](https://img.shields.io/github/workflow/status/programmer290399/pyqna/Python%20application?style=for-the-badge)
     - [ ] Last activity
         ![last-commit](https://img.shields.io/github/last-commit/programmer290399/pyqna?style=for-the-badge)
     - [ ] code coverage [Not yet setup]
     - [ ] Open Issues
         ![open-issues](https://img.shields.io/github/issues-raw/programmer290399/pyqna?style=for-the-badge)
     - [ ] License 
         ![license](https://img.shields.io/pypi/l/pyqna?style=for-the-badge)

- [ ] Add Installation instructions 
- [ ] Add a simple example 
- [ ] Add licence information
