### ISSUE TITLE
contrib: Add contribution related documentation 

### ISSUE THREAD

**Issue by programmer290399** [programmer290399/pyqna#6]
## TODO: 
- [ ] Add a guideline for contribution in a markdown file from CONTRIBUTING.rst 
- [ ] Add documentation on how to setup a development workflow 
- [ ] Add a PR template 
- [ ] Add issue Templates 
- [ ] Add linting checks for style and consistency 
- [ ] Update CONTRIBUTING.rst
